
server.port=8585

server.servlet.context-path=/workintech

spring.devtools.restart.enabled=true

management.endpoints.web.exposure.include=*

info.app.name=Workintech Developer API
info.app.description=Spring Boot Dependency Injection Project
info.app.version=1.0.0